### ISSUE TITLE
RGCA: Backlit regularization should go on until end of training

### ISSUE THREAD

**Issue by una-dinosauria** [facebookresearch/goliath#11]
Currently, backlit reg is configured like this:

```
    backlit_reg:
      schedule:
        class_name: ca_code.loss.StepWeightSchedule
        start: 500000
        end: 600000
        value: 1.0
```

If we train for longer (eg, 800k iterations) then backlit regularization turns off. We should enable it until the end of training.

Backlit artifacts:
https://github.com/user-attachments/assets/fa2f6ebe-ffef-42e5-b97b-5841a372f53e
